### ISSUE TITLE
read.table in fetch_dataset() does not give the desired result

### ISSUE THREAD

**Issue by IZE85** [enricoschumann/BISdata#1] opened 2022-10-05 10:16 UTC
Hi there,
could it be that there is a problem in the use of the "read.table" function in the "fetch_dataset()" function? 

The BIS data is read in and an R object is created, although not properly. It could be that this concerns only the "full_credit_gap_csv.zip" and hence the "WS_CREDIT_GAP_csv_col.csv" file. I haven't looked at other BIS datasets yet.
The "strip.white = TRUE" argument in read.table kind of helps, but still the file is not 100% correctly read in.

The following code produces the following "Warning message" (after specifying a user-specific dest.dir):

Code:
bis.data <- fetch_dataset(dest.dir = dest.dir,
                            dataset = "full_credit_gap_csv.zip",
                            bis.url = "https://www.bis.org/statistics/",
                            exdir = dest.dir)

Warning message:
In read.table(tmp, header = TRUE, sep = ",", stringsAsFactors = FALSE,  :
  incomplete final line found by readTableHeader on 'data/raw/BIS_data/WS_CREDIT_GAP_csv_col.csv'"

Thank you for your package!

**Comment by enricoschumann** [comment] 2022-10-05 18:47
Matthias, thank you for the report. I cannot reproduce the error/warning. Could you please tell me on what platform (OS, R version, etc.) you work? Also, could you try to remove the downloaded zip file from the `dest.dir`, and then try again? (If the download somehow failed but a file was written anyway, then `fetch_dataset` will still try to read/parse the downloaded, corrupted file, and so will always fail.)

**Comment by IZE85** [comment] 2022-10-05 18:56
Hi Enrico,

thank you for your reply.

I work on Mac OS X Big Sur 11.7 and R 4.2.1.

I tried your suggestion, but unfortunately it did not work to correctly read in the extracted file.

Here’s a screenshot on how the R object looks like in „View()“.



Kind regards,
Matt

**Comment by enricoschumann** [comment] 2022-10-05 19:08
I don't see a screenshot?

**Comment by IZE85** [comment] 2022-10-05 19:20
my bad, here is the screenshot.
![screenshot1](https://user-images.githubusercontent.com/70013636/194144282-c735be13-b2f1-422d-8cd5-166137a8d803.jpg)

**Comment by enricoschumann** [comment] 2022-10-05 19:41
That is weird. It looks like the raw CSV file.
Could you try the following, please:

## choose a dest.dir
dest.dir <- "~/Downloads/BIS"


## download and process the file
f.path <- file.path(dest.dir, "full_credit_gap_csv.zip")
download.file("https://www.bis.org/statistics/full_credit_gap_csv.zip",
              f.path)

tmp <- unzip(f.path, exdir = tempdir())
txt <- read.table(tmp, header = TRUE, sep = ",",
                  stringsAsFactors = FALSE,
                  check.names = FALSE,
                  na.strings = "",
                  quote = "",
                  fill = TRUE)

**Comment by IZE85** [comment] 2022-10-05 20:00
actually, this works perfectly fine!

**Comment by enricoschumann** [comment] 2022-10-06 05:31
Thanks. You are using the CRAN version of package, i.e. 0.1-1? If yes, could you please try [version 0.2-0](http://enricoschumann.net/R/packages/BISdata/)?

```r
install.packages('BISdata',
                 repos = c('http://enricoschumann.net/R', getOption('repos')))
```

**Comment by IZE85** [comment] 2022-10-06 07:38
Indeed, I was using 0.1-1, which is on CRAN. I tried your version 0.2-0 and now everything works as desired. Thank you!

**Comment by enricoschumann** [comment] 2022-10-06 07:53
Great!

(The trouble came because several datasets use apostrophes in column names. But those are interpreted by read.table, by default, as quotation marks. The newer version had already fixed this.  I only never sent it to CRAN; but I will do so today.  Thanks again for reporting the issue.)

**Comment by IZE85** [comment] 2022-10-06 08:05
Thank you for sharing your package!

**Comment by enricoschumann** [comment] 2022-10-06 11:11
Version 0.2-0 is now on CRAN: [https://cran.r-project.org/package=BISdata](https://cran.r-project.org/package=BISdata) I close this issue now. Feel free to reopen if something does not work as expected.

**Comment by IZE85** [comment] 2022-10-06 11:12
awesome! thank you!

**Closed as completed by enricoschumann** 2022-10-06 11:11 UTC
